name: projet
description: TM Project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio:
  json_annotation: ^4.7.0
  bloc:
  flutter_bloc:
  intl:
  firebase_core: ^2.2.0
  cloud_firestore:
  auto_route:
  equatable:
  vibration:
  adaptive_theme:
  flutter_launcher_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator:
  build_runner:
  bloc:
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/